# this file is used by mkdocs to build the site and theme it https://www.mkdocs.org/
site_name: Maestro
docs_dir: docs
markdown_extensions:
    - toc:
        permalink: "#"
nav:
- Introduction: intro.md
- Features : features.md
- Setup: setup.md
- Usage: usage.md
- 'Code & Archeticture': tech.md  

theme: readthedocs