def commit = "UNKNOWN"

pipeline {
    agent {
        kubernetes {
            label 'maestro-executor'
            yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: java
    image: openjdk:11-jdk-slim
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
  - name: docker
    image: docker:18-git
    tty: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
      type: File
"""
        }
    }
    stages {
        stage('Build') {
            steps {
                container('java') {
                    sh 'ls'
                    // TODO replace with real command
                    sh './mvnw release version ${version} !!'
                }
                container('docker') {
                    withCredentials([usernamePassword(credentialsId:'OvertureDockerHub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                        sh 'docker login -u $USERNAME -p $PASSWORD'
                    }
                    // the netowrk=host needed to download dependencies using the host network (since we are inside 'docker'
                    // container)
                    // TODO: consider using the maven dockerfile to release & push stuff
                    sh "docker  build --build-arg VERSION=${version} --network=host -f Dockerfile ../../ -t overture/maestro:${version}"
                    // should change to have a release version instead of commit# as tag
                    sh "docker push overture/maestro:${version}"
                }
            }
        }
    }
    post {
        always {
            junit "**/TEST-*.xml"
        }
    }
}