version: '3'
services:
  maestro:
    image: overture/maestro:0.0.1-SNAPSHOT
    container_name: maestro
    ports:
      - 11235:11235
    environment:
      - ELASTICSEARCH.CLUSTER.NODES=maestro.elasticsearch:9200
      - ELASTICSEARCH.CLUSTER.NAME=maestro.elasticsearch
      - logging.level.root=INFO
      - spring.boot.admin.client.url=http://boot-admin:1122
      - management.health.elasticsearch.enabled=false
      - management.security.enabled=false
    depends_on:
       - elasticsearch
  admin:
    image: basharlabadi/vanilla-admin-boot:0.0.2
    environment:
      - spring.boot.admin.security.enabled=false
    ports:
      - 1122:1122
    healthcheck:
      test: "curl -sS http://localhost:1111/health"
      interval: 1s
      timeout: 60s
      retries: 120
    container_name: boot-admin
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
    container_name: maestro.elasticsearch
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - cluster.name=maestro.elasticsearch
      - "ES_JAVA_OPTS=-Xms512m -Xmx2048m"
