server:
  port: 11235

spring:
  application:
    name: maestro
  output.ansi.enabled: ALWAYS


maestro:
  exclusion-rules:
    file-name: exlusion-rules.yml
  # elastic search server & client props
  elasticsearch:
    cluster-name: maestro.elasticsearch
    cluster-nodes: localhost:9200, localhost:9201
    indexes:
      file-centric:
        alias: file_centric
    client:
      # this is to control the number of documents per bulk request in elasticsearch
      docs-per-bulk-req-max: 5000
      # max time to wait for a connection to be established
      connection-timeout: 5000
      # max time to wait on idle connection (no data flow)
      socket-timeout: 10000

  # Genome file repositories props
  repositories:
      # must be unique
    - code: collab
      url: https://song.cancercollaboratory.org
      name: collaboratory
      dataPath: /oicr.icgc/data
      metadataPath: /oicr.icgc.meta/metadata
      # optional
      storageType: S3
      organization: ICGC
      country: CA

# logging & monitoring
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd} | %d{HH:mm:ss.SSS}){blue} | %clr(%t){cyan} | %clr(${PID}){faint} | %clr(%p) | %clr(%logger){blue} | %clr(%m){faint}%n"
  level:
    root: INFO
    bio.overture: TRACE

# spring boot actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS