maestro:
  elasticsearch:
    indexes:
      file-centric:
        alias: file-centric
  repositories:
    - code: collab
      url: https://song.cancercollaboratory.org
      name: collaboratory
      dataPath: /oicr.icgc/data
      metadataPath: /oicr.icgc.meta/metadata
      storageType: S3
      organization: ICGC
      country: CA
    - code: aws
      url: http://aws.amazon.com
      name: aws repo
      country: US
spring:
  data:
    elasticsearch:
      cluster-name: maestro.elasticsearch
      cluster-nodes: localhost:9300
