def commit = "UNKNOWN"

pipeline {
    agent {
        kubernetes {
            label 'maestro-executor'
            yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jdk
    image: openjdk:11-jdk-slim
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
  - name: docker
    image: docker:18-git
    tty: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
      type: File
"""
        }
    }
    stages {
        stage('Build') {
            steps {
                container('jdk') {
                    sh 'ls'
                    sh './mvnw test'
                }
            }
        }
        stage('publish artifacts') {
            //when {
            //    branch 'develop'
            //}
            steps {
                container('docker') {
                    withCredentials([usernamePassword(credentialsId:'OvertureDockerHub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                     sh 'docker login -u $USERNAME -p $PASSWORD'
                    }

                    script {
                        commit = sh(returnStdout: true, script: 'git describe --always').trim()
                    }

                    // the netowrk=host needed to download dependencies using the host network (since we are inside 'docker'
                    // container)
                    sh "docker  build --network=host -f develop/Dockerfile .. -t overture/maestro:edge -t overture/maestro:${commit}"
                    sh "docker push overture/maestro:edge"
               }
            }
        }
    }
    post {
        always {
            junit "**/TEST-*.xml"
        }
    }
}